CedarCreek/Controllers/CharactersController.cs
using Microsoft.AspNetCore.Mvc;
using CedarCreek.Data;
using CedarCreek.Models.Characters;
using CedarCreek.Core.ServiceInterface;
using CedarCreek.ApplicationServices.Services;
using CedarCreek.Core.Dto;
using CedarCreek.Core.Domain;
using static System.Net.Mime.MediaTypeNames;
using Microsoft.EntityFrameworkCore;
using CharacterClass = CedarCreek.Core.Domain.CharacterClass;
using CharacterStatus = CedarCreek.Core.Domain.CharacterStatus;
using Microsoft.AspNetCore.Components.Web;

namespace CedarCreek.Controllers
{
	public class CharactersController : Controller
	{
		//This controls all functions for characters, including missions.

		private readonly CedarCreekContext _context;
		private readonly ICharactersServices _charactersServices;
		private readonly IFileServices _fileServices;

		public CharactersController(CedarCreekContext context, ICharactersServices charactersServices, IFileServices fileServices)
		{
			_context = context;
			_charactersServices = charactersServices;
			_fileServices = fileServices;
		}
		[HttpGet]
		public IActionResult Index()
		{
			var resultingInventory = _context.Characters
				.OrderByDescending(y => y.CharacterLevel)
				.Select(x => new CharacterListIndexViewModel
				{
					ID = x.ID,
					CharacterName = x.CharacterName,
					CharacterClass = (Models.Characters.CharacterClass)x.CharacterClass,
					CharacterLevel = x.CharacterLevel,
				});
			return View(resultingInventory);
		}
		[HttpGet]
		public IActionResult Create()
		{
			CharacterCreateViewModel vm = new();
			return View("Create", vm);
		}
		[HttpPost, ActionName("Create")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create(CharacterCreateViewModel vm)
		{
			var dto = new CharacterDto
			{
				CharacterName = vm.CharacterName,
				CharacterHealth = 100,
				CharacterXP = 0,
				CharacterXPNextLevel = 100,
				CharacterLevel = 0,
				CharacterClass = (Core.Dto.CharacterClass)vm.CharacterClass,
				CharacterStatus = (Core.Dto.CharacterStatus)vm.CharacterStatus,
				PrimaryAttackName = vm.PrimaryAttackName,
				PrimaryAttackPower = vm.PrimaryAttackPower,
				SpecialAttackName = vm.SpecialAttackName,
				SpecialAttackPower = vm.SpecialAttackPower,
				CharacterCreationTime = vm.CharacterCreationTime,
				Files = vm.Files,
				Image = vm.Image.Select(x => new FileToDatabaseDto
				{
					ID = x.ImageID,
					ImageData = x.ImageData,
					ImageTitle = x.ImageTitle,
					CharacterID = x.CharacterID,
				}).ToArray()
            };
			var result = await _charactersServices.Create(dto);

			if (result == null)
			{
				return RedirectToAction("Index");
			}
            return RedirectToAction("Index", vm);
        }
		[HttpGet]
		public async Task<IActionResult> Details(Guid id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var character = await _charactersServices.DetailsAsync(id);

			if (character == null)
			{
				return NotFound();
			}
			

			var images = await _context.FilesToDatabase
				.Where(c => c.CharacterID == id)
				.Select(y => new CharacterImageViewModel
				{
				CharacterID = y.ID,
					ImageID = y.ID,
					ImageData = y.ImageData,
					ImageTitle = y.ImageTitle,
					Image = string.Format("data:image/gif;base64{0}", Convert.ToBase64String(y.ImageData))
				}).ToArrayAsync();
			var vm = new CharacterDetailsViewModel();
            vm.CharacterName = vm.CharacterName;
            vm.CharacterHealth = 100;
            vm.CharacterXP = 0;
            vm.CharacterXPNextLevel = 100;
            vm.CharacterLevel = 0;
			vm.CharacterClass = (Models.Characters.CharacterClass)character.CharacterClass;
			vm.CharacterStatus = (Models.Characters.CharacterStatus)character.CharacterStatus;
            vm.PrimaryAttackName = vm.PrimaryAttackName;
            vm.PrimaryAttackPower = vm.PrimaryAttackPower;
            vm.SpecialAttackName = vm.SpecialAttackName;
            vm.SpecialAttackPower = vm.SpecialAttackPower;
            vm.CharacterCreationTime = vm.CharacterCreationTime;

			return View(vm);
		}
		[HttpGet]
		public async Task<IActionResult> Update(Guid id)
		{
			if (id == null) { return NotFound(); }

			var character = await _charactersServices.DetailsAsync(id);

			if (id == null) { return NotFound(); }

			var images = await _context.FilesToDatabase
				.Where(x => x.CharacterID == id)
				.Select(y => new CharacterImageViewModel
				{
					CharacterID = y.ID,
					ImageID = y.ID,
					ImageData = y.ImageData,
					ImageTitle = y.ImageTitle,
					Image = string.Format("data:image/gif;base64{0}", Convert.ToBase64String(y.ImageData))
				}).ToArrayAsync();

            var vm = new CharacterCreateViewModel();
            vm.CharacterName = vm.CharacterName;
            vm.CharacterHealth = 100;
            vm.CharacterXP = 0;
            vm.CharacterXPNextLevel = 100;
            vm.CharacterLevel = 0;
            vm.CharacterClass = (Models.Characters.CharacterClass)character.CharacterClass;
            vm.CharacterStatus = (Models.Characters.CharacterStatus)character.CharacterStatus;
            vm.PrimaryAttackName = vm.PrimaryAttackName;
            vm.PrimaryAttackPower = vm.PrimaryAttackPower;
            vm.SpecialAttackName = vm.SpecialAttackName;
            vm.SpecialAttackPower = vm.SpecialAttackPower;
            vm.CharacterCreationTime = vm.CharacterCreationTime;

			return View("Update", vm);
        }
		[HttpPost]
		public async Task<IActionResult> Update(CharacterCreateViewModel vm)
		{
			var dto = new CharacterDto()
			{
				ID = (Guid)vm.ID,
				CharacterName = vm.CharacterName,
				CharacterHealth = 100,
				CharacterXP = 0,
				CharacterXPNextLevel = 100,
				CharacterLevel = 0,
				CharacterClass = (Core.Dto.CharacterClass)vm.CharacterClass,
				CharacterStatus = (Core.Dto.CharacterStatus)vm.CharacterStatus,
				PrimaryAttackName = vm.PrimaryAttackName,
				PrimaryAttackPower = vm.PrimaryAttackPower,
				SpecialAttackName = vm.SpecialAttackName,
				SpecialAttackPower = vm.SpecialAttackPower,
				CharacterCreationTime = vm.CharacterCreationTime,
				Files = vm.Files,
				Image = vm.Image.Select(x => new FileToDatabaseDto
				{
					ID = x.ImageID,
					ImageData = x.ImageData,
					ImageTitle = x.ImageTitle,
					CharacterID = x.CharacterID,
				}).ToArray(),
			};
			var result = await _charactersServices.Update(dto);
			
			if (result == null)
			{
				return RedirectToAction("Index"); 
			}
			return RedirectToAction("Index", vm);
		}
		[HttpGet]
		public async Task<IActionResult> Delete(Guid id)
		{
			if (id == null) { return NotFound(); }

			var character = await _charactersServices.DetailsAsync(id);

			if (id == null) { return NotFound(); };

			var images = await _context.FilesToDatabase
				.Where(x => x.CharacterID == id)
				.Select( y => new CharacterImageViewModel
				{
					CharacterID = y.ID,
					ImageID = y.ID,
					ImageData = y.ImageData,
					ImageTitle = y.ImageTitle,
					Image = string.Format("data:image/gif;base64,{0}", Convert.ToBase64String(y.ImageData))
				}).ToArrayAsync();
			var vm = new CharacterDeleteViewModel();

			vm.ID = character.ID;
			vm.CharacterName = character.CharacterName;
			vm.CharacterHealth = 100;
			vm.CharacterXP = 0;
			vm.CharacterXPNextLevel = 100;
			vm.CharacterLevel = 0;
			vm.CharacterClass = (Models.Characters.CharacterClass)character.CharacterClass;
			vm.CharacterStatus = (Models.Characters.CharacterStatus)character.CharacterStatus;
			vm.PrimaryAttackName = character.PrimaryAttackName;
			vm.PrimaryAttackPower = character.PrimaryAttackPower;
			vm.SpecialAttackName = character.SpecialAttackName;
			vm.SpecialAttackPower = character.SpecialAttackPower;
			vm.CharacterCreationTime = character.CharacterCreationTime;
			vm.Image.AddRange(images);
			
			return View(vm);
		}
		[HttpPost]
		public async Task<IActionResult> DeleteConfirmation(Guid id)
		{
			var characterToDelete = await _charactersServices.Delete(id);

			if (characterToDelete == null) { return RedirectToAction("Index"); }

			return RedirectToAction("Index");
		}
		[HttpPost]
		public async Task<IActionResult> RemoveImage(CharacterImageViewModel vm)
		{
			var dto = new FileToDatabaseDto()
			{
				ID = vm.ImageID
			};
			var image = await _fileServices.RemoveImageFromDatabase(dto);
			if (image == null) { return RedirectToAction("Index"); }
			return RedirectToAction("Index");
		} 
	}
}

CedarCreek/Controllers/RealmsController.cs
using CedarCreek.ApplicationServices.Services;
using CedarCreek.Core.Dto;
using CedarCreek.Core.ServiceInterface;
using CedarCreek.Data;
using CedarCreek.Models.Characters;
using CedarCreek.Models.Realms;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CedarCreek.Controllers
{
    public class RealmsController : Controller
	{
		private readonly CedarCreekContext _context;
		private readonly IRealmsServices _realmsServices;
		private readonly IFileServices _fileServices;

		public RealmsController(CedarCreekContext context, IRealmsServices realmsServices, IFileServices fileServices)
		{
			_context = context;
			_realmsServices = realmsServices;
			_fileServices = fileServices;
		}

		[HttpGet]
		public IActionResult Index()
		{
			var resultingInventory = _context.Realms
				.OrderByDescending(y => y.CreatedAt)
				.Select(x => new RealmListIndexViewModel
				{
					ID = x.ID,
					RealmName = x.RealmName,
					RealmEffect = (Models.Realms.RealmEffect)x.RealmEffect,
					CharacterLevelRequirement = x.CharacterLevelRequirement,
				});
			return View(resultingInventory);
		}
		[HttpGet]
		public IActionResult Create()
		{
			RealmCreateViewModel vm = new();
			return View("Create", vm);
		}
		[HttpPost]
		public async Task<IActionResult> Create(RealmCreateViewModel vm)
		{
			var dto = new RealmDto
			{
				RealmName = vm.RealmName,
				RealmEffect = (Core.Dto.RealmEffect)vm.RealmEffect,
				CharacterLevelRequirement = vm.CharacterLevelRequirement,
				Files = vm.Files,
				Image = vm.Image.Select(x => new FileToDatabaseDto
				{
					ID = x.ImageID,
					ImageData = x.ImageData,
					ImageTitle = x.ImageTitle,
					RealmID = x.RealmID,
				}).ToArray()
			};
			var result = await _realmsServices.Create(dto);
			if (result != null) 
			{
				return RedirectToAction("Index");
			}
			return RedirectToAction("Index", vm);
		}
		[HttpGet]
		public async Task<IActionResult> Details(Guid id)
		{
			if (id == null)
			{
				return NotFound();
			}
			var Realm = await _realmsServices.DetailsAsync(id);

			if (Realm == null)
			{
				return NotFound();
			}

            var images = await _context.FilesToDatabase
			.Where(c => c.CharacterID == id)
			.Select(y => new RealmImageViewModel 
			{
				RealmID = y.ID,
				ImageID = y.ID,
				ImageData = y.ImageData,
				ImageTitle = y.ImageTitle,
				Image = string.Format("data:image/gif;base64{0}", Convert.ToBase64String(y.ImageData))
			}).ToArrayAsync();
			var vm = new RealmDetailsViewModel();
			vm.RealmName = vm.RealmName;
			vm.RealmEffect = vm.RealmEffect;
			vm.CharacterLevelRequirement = vm.CharacterLevelRequirement;
			vm.Files = vm.Files;
			return View(vm);
        }
		[HttpGet]
		public async Task<IActionResult> Delete(Guid id)
		{
			if (id == null)
			{
				return NotFound();
			}
			var Realm = await _realmsServices.DetailsAsync(id);

			if (Realm == null)
			{
				return NotFound();
			}

			var images = await _context.FilesToDatabase
			.Where(c => c.CharacterID == id)
			.Select(y => new RealmImageViewModel
			{
				RealmID = y.ID,
				ImageID = y.ID,
				ImageData = y.ImageData,
				ImageTitle = y.ImageTitle,
				Image = string.Format("data:image/gif;base64{0}", Convert.ToBase64String(y.ImageData))
			}).ToArrayAsync();
			var vm = new RealmDetailsViewModel();
			vm.RealmName = vm.RealmName;
			vm.RealmEffect = vm.RealmEffect;
			vm.CharacterLevelRequirement = vm.CharacterLevelRequirement;
			vm.Files = vm.Files;
			return View(vm);
		}
		[HttpPost]
		public async Task<IActionResult> DeleteConfirmation(Guid id)
		{
			var realmToDelete = await _realmsServices.Delete(id);

			if (realmToDelete == null) { return RedirectToAction("Index"); }

			return RedirectToAction("Index");
		}
	}
}

CedarCreek/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<CedarCreek.Core.Domain.ApplicationUser> signInManager;
@inject CedarCreek.Core.Domain.PlayerProfile playerProfile;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CedarCreek</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CedarCreek.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CedarCreek</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                       @* @if(signInManager.IsSignedIn(User))
                        {
                            if (playerProfile.ProfileType == true)
                            { *@
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Characters" asp-action="Index">My Characters</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Realms" asp-action="Index">the Realm</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Accounts" asp-action="Register">Register</a>
                                </li>
                    @*        }
                        }    *@
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - CedarCreek - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>