CedarCreek/Controllers/PlayerProfilesController.cs
using CedarCreek.Core.Domain;
using CedarCreek.Core.Dto.AccountsDtos;
using CedarCreek.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CedarCreek.Controllers
{
    public class PlayerProfilesController : Controller
    {
        private readonly CedarCreekContext _context;
        public PlayerProfilesController(CedarCreekContext context)
        {
            _context = context;
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return View(_context.PlayerProfiles.OrderByDescending(x => x.ScreenName));
        }
        [HttpGet]
        public async Task<IActionResult> NewProfile()
        {
            return View();
        }

        [HttpPost]
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public async Task<IActionResult> NewProfile(PlayerProfileDto dto)
        {
            string userid = (string)TempData["NewUserID"];
            if (dto.ApplicationUserID == null)
            {
                return RedirectToAction("Index");
            }

            var newprofile = new PlayerProfile()
            {
                ID = dto.Id,
                ApplicationUserID = dto.ApplicationUserID,
                MyCharacters = new List<CharacterOwnership>(),
                ScreenName = "",
                Gold = 25,
                Momentos = 0,
                Victories = 0,
                CurrentStatus = ProfileStatus.Active,
                ProfileType = false
            };
            var result = await _context.PlayerProfiles.AddAsync(newprofile);
            if (result != null)
            {
                return View(Index());
            }
            return null;
        }
        [HttpGet]
        public async Task<IActionResult> NewPlayerProfile()
        {
            return View();
        }
    }
}

CedarCreek/Views/PlayerProfiles/NewProfile.cshtml
@model CedarCreek.Models.Profiles.ProfileRegisterViewModel

<div class="">
	<h1> Customize your profile: </h1>
</div>

<div class="row">
	<div class="col-md-12">
		<form method="post">

			<div asp-validation-summary="All" class="">
				<input type="hidden" asp-for="ApplicationUserID"/>
				<input type="hidden" asp-for="ScreenName"/>
				<input type="hidden" asp-for="Gold" />
				<input type="hidden" asp-for="ProfileType" />
				<input type="hidden" asp-for="Victories" />

			</div>
			<div class="form-group">
				<label asp-for="ScreenName"></label>
				<input asp-for="ScreenName" class="form-control" />
				<span asp-validation-for="ScreenName" class=""></span>
			</div>

			<button type="submit">
				<a asp-route-id=@ViewData["NewUserID"] id="" viewBox="0 0 200 50"
				   asp-controller="PlayerProfiles" asp-action="NewProfile">	
					<svg id="indexButton" class="">
						<rect class=""></rect>
						<text x="10" y="21"class="">This is the text</text>
						<polygon class="" points="0,0 0,13 13,0"></polygon>
						<polygon class="" points="130,30 130,17 117,30"></polygon>
					</svg>
				</a>
			</button>
		</form>
	</div>
</div>